image: golang:1.16

stages:
  - build
  - lint
  - test
  - deploy

build:
  stage: build
  script:
    - make build
  tags:
    - docker

fmt-check:
  stage: lint
  script:
    - make fmt-check
  only:
    - branches
  tags:
    - docker

lint:
  stage: lint
  script:
    - make lint
  only:
    - branches
  tags:
    - docker

static-check:
  stage: lint
  script:
    - make staticcheck
  only:
    - branches
  tags:
    - docker

vet:
  stage: lint
  script:
    - make vet
  only:
    - branches
  tags:
    - docker

unit-test:
  stage: test
  script:
    - make test
  only:
    - branches
  tags:
    - docker

coverage:
  stage: test
  coverage: /total:.*\d+\%|total:.*\d+.\d+\%/
  script:
    - make coverage-cobertura
  artifacts:
    reports:
      cobertura: build/coverage/cobertura.xml
  only:
    - branches
  tags:
    - docker

publish:
  stage: deploy
  extends: build
  artifacts:
    paths:
      - bin/jiracli
  tags:
    - docker
